### ISSUE TITLE
Browserify key in package.json

### ISSUE THREAD

**Issue by marekhrabe** [cezary/react-favicon#1]
Is it necessary? Seems like it is not used at all. It prevented me to use the npm module as a dependency of my (browserify) app, because of missing `reactify` module.

**Comment by cezary** [comment]
No, not necessary must be a leftover property I forgot to remove. I'll clean it up later today.

**Comment by cezary** [comment]
2d81d61ed5a20422893d6e040fc6ed43583a13d6 should fix it
