### ISSUE TITLE
Upgrade to React v0.14

### ISSUE THREAD

**Issue by danistefanovic** [cezary/react-favicon#2]
The current available version is [React v0.14.6](https://github.com/facebook/react/releases). The peer dependency definition of react-favicon is `"react": ">=0.12.0 < 0.14.0"`

**Comment by scheung38** [comment]
Me too. In Win 7:

>meteor npm install react-favicon --save
npm WARN peerDependencies The peer dependency react@>=0.12.0 < 15.0.x included from react-favicon will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\SEC11\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.2_4\\mt-os.windows.x86_32\\dev_
bundle\\bin\\\\node.exe" "C:\\Users\\seb\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.2_4\\mt-os.windows.x
86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-favicon" "--save"
npm ERR! node v0.10.43
npm ERR! npm  v2.14.22
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer griddle-react@0.5.1 wants react@^0.14.3 || ^15.0.1
npm ERR! peerinvalid Peer react-bootstrap-datetimepicker@0.0.22 wants react@>=0.14
npm ERR! peerinvalid Peer react-dom@15.1.0 wants react@^15.1.0
npm ERR! peerinvalid Peer react-mounter@1.2.0 wants react@0.14.x || 15.x.x
npm ERR! peerinvalid Peer react-addons-css-transition-group@15.1.0 wants react@^15.1.0
npm ERR! peerinvalid Peer react-toolbox@0.16.2 wants react@^0.14 || ^15.0.1
npm ERR! peerinvalid Peer react-favicon@0.0.4 wants react@>=0.12.0 < 15.0.x

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\seb\PycharmProjects\spark2acs\npm-debug.log

How to resolve this? I need to install webpack?
